In [ ]:
#sentence embedding

In [2]:
pip install tensorflow_hub

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 1.7 MB 1.8 MB/s eta 0:00:01
     |████████████████████████████████| 236.1 MB 68.1 MB/s eta 0:00:01
     |████████████████████████████████| 3.0 MB 23.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.1 MB 57.6 MB/s eta 0:00:01
     |████████████████████████████████| 390 kB 22.6 MB/s eta 0:00:01
     |████████████████████████████████| 5.5 MB 52.8 MB/s eta 0:00:01
     |████████████████████████████████| 240 kB 38.1 MB/s eta 0:00:01
     |████████████████████████████████| 282 kB 45.7 MB/s eta 0:00:01
     |████████████████████████████████| 87 kB 20.6 MB/s eta 0:00:01
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Successfully uninstalled h5py

In [4]:
pip install tensorflow_text

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 6.1 MB 1.4 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [5]:
import tensorflow_hub as hub
import tensorflow_text as text

In [6]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3" #it preprocesses the text
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [8]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)

In [9]:
#suppose i am building a movie classification
text_test=["nice movie indeed",'I love python programming']
text_preprocessed= bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [10]:
text_preprocessed['input_mask'] #CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [14]:
bert_models=hub.KerasLayer(encoder_url)
bert_results= bert_models(text_preprocessed)
bert_results.keys()

dict_keys(['default', 'encoder_outputs', 'pooled_output', 'sequence_output'])

In [15]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917738 , -0.21411915,  0.49769527, ...,  0.2446523 ,
        -0.47334468,  0.8175867 ],
       [-0.917123  , -0.47935164, -0.7865694 , ..., -0.617517  ,
        -0.71026844,  0.9218429 ]], dtype=float32)>

In [16]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292045,  0.08567807,  0.14476861, ..., -0.09677105,
          0.0872214 ,  0.07711077],
        [ 0.17839377, -0.19006099,  0.5034939 , ..., -0.05869853,
          0.3271714 , -0.15578558],
        [ 0.18701519, -0.43388748, -0.48875126, ..., -0.15502785,
          0.00145189, -0.24470949],
        ...,
        [ 0.12083046,  0.12884232,  0.46453544, ...,  0.07375513,
          0.17441958,  0.1652209 ],
        [ 0.07967914, -0.0119064 ,  0.5022541 , ...,  0.13777715,
          0.21002248,  0.00624602],
        [-0.07212668, -0.28303444,  0.59033406, ...,  0.47551912,
          0.16668507, -0.08920383]],

       [[-0.07900566,  0.36335117, -0.21101572, ..., -0.17183729,
          0.16299763,  0.67242676],
        [ 0.27883598,  0.4371629 , -0.35764766, ..., -0.04463641,
          0.3831525 ,  0.5887988 ],
        [ 1.2037673 ,  1.0727023 ,  0.48408777, ...,  0.24921033,
          0.4073094 ,  0.4048179 ],
        ...,

In [17]:
bert_results['encoder_outputs'][-1]== bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>